"use client"

import type React from "react"
import { createContext, useContext, useState, useEffect } from "react"

type Language = "en" | "fr"

interface LanguageContextType {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  en: {
    // Navigation sections
    "nav.main": "Main Navigation",
    "nav.services": "Services",
    "nav.user-management": "User Management",
    "nav.additional": "Additional",

    // Navigation items
    "nav.dashboard": "Dashboard",
    "nav.topup": "Prepaid Recharge",
    "nav.wallet": "My Wallet",
    "nav.reports": "Reports",
    "nav.contact": "Contact Us",
    "nav.sim-sales": "SIM Sales",
    "nav.packages": "Packages",
    "nav.bills": "Bill Payment",
    "nav.onboarding": "Onboarding",
    "nav.jobs": "Job Cards",
    "nav.inventory": "Inventory",
    "nav.profile": "Profile",
    "nav.notifications": "Notifications",
    "nav.support": "Support",
    "nav.funds": "Fund Request",
    "nav.feedback": "Feedback",
    "nav.about": "About",

    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle": "Welcome back, manage your services and track performance",
    "dashboard.support.title": "24/7 Customer Support",
    "dashboard.support.description": "Our dedicated support team is here to help you with all your queries and issues.",
    "dashboard.support.button": "Contact Support",
    "dashboard.popular-services": "Popular Services",
    "dashboard.transactions": "transactions",

    // KPIs
    "kpi.sales": "Today's Sales",
    "kpi.transactions": "Transactions",
    "kpi.customers": "Active Customers",
    "kpi.success": "Success Rate",

    // Services
    "services.title": "Quick Services",
    "services.mobile-topup": "Mobile Prepaid Recharge", // Changed Mobile Top-up to Mobile Prepaid Recharge
    "services.data-packages": "Data Packages",
    "services.bill-payment": "Bill Payment",
    "services.fund-request": "Fund Request",
    "services.sim-sales": "SIM Sales",
    "services.job-cards": "Job Cards",

    // Transactions
    "transactions.title": "Recent Transactions",
    "transactions.view-all": "View All",
    "transactions.pending": "Pending",
    "transactions.completed": "Completed",

    // Fund Request
    "funds.title": "Fund Request Center",
    "funds.new-request": "New Request",
    "funds.available": "Available Funds",
    "funds.pending": "Pending Requests",
    "funds.monthly-limit": "Monthly Limit",

    // Support
    "support.title": "Support & Notifications",
    "support.sim-not-working": "SIM card not working",
    "support.payment-error": "Unable to process payment",
    "support.help-docs": "Help Documentation",
    "support.contact-support": "Contact Support",
    "support.feedback": "Provide Feedback",
    "support.customer": "Customer",
    "support.high": "High",

    // Theme
    "theme.blue": "Blue",
    "theme.purple": "Purple",

    // Language
    "language.english": "English",
    "language.french": "Français",

    // Carousel
    "carousel.roaming-data": "Roaming Data Booster",
    "carousel.5g-unlimited": "5G Unlimited Plans",
    "carousel.special-offer": "Special Offers",
    "carousel.esim": "eSIM Solutions",

    // Reports page
    "reports.title": "Reports",
    "reports.subtitle": "Business analytics and performance tracking",
    "reports.export": "Export Data",
    "reports.today": "Today",
    "reports.week": "This Week",
    "reports.month": "This Month",
    "reports.custom": "Custom Range",
    "reports.pick-date": "Pick a date range",
    "reports.total-sale": "Total Sale",
    "reports.total-transactions": "Total Transactions",
    "reports.earnings": "Earnings",
    "reports.sim-stock": "SIM Stock",
    "reports.airtime": "Airtime Purchase",
    "reports.balance": "Balance",
    "reports.quick-actions": "Quick Report Actions",
    "reports.sales-report": "Sales Report",
    "reports.customer-report": "Customer Report",
    "reports.inventory-report": "Inventory Report",
    "reports.description": "View comprehensive business analytics and performance metrics",
    "reports.customRange": "Custom Range",
    "reports.pickDateRange": "Pick a date range",
    "reports.exportData": "Export Data",
    "reports.quickActionsDesc": "Access frequently used reports and analytics",

    // Contact page
    "contact.title": "Contact Us",
    "contact.subtitle": "Get in touch with our support team",
    "contact.phone-support": "Phone Support",
    "contact.phone-desc": "Call us for immediate assistance",
    "contact.email-support": "Email Support",
    "contact.email-desc": "Send us your questions via email",
    "contact.office-location": "Office Location",
    "contact.office-desc": "Visit our main office",
    "contact.business-hours": "Business Hours",
    "contact.customer-service": "Customer Service",
    "contact.emergency-support": "Emergency Support",
    "contact.additional-resources": "Additional Resources",
    "contact.call-now": "Call Now",
    "contact.send-email": "Send Email",
    "contact.view-map": "View on Map",
    "contact.website": "Website",
    "contact.callback": "Callback Request",
    "contact.description": "Get in touch with our support team for assistance",
    "contact.supportLineNorthCentral": "Support Line (North & Central)",
    "contact.supportLineSouthCentral": "Support Line (South & Central)",
    "contact.supportLinePraslinLaDigue": "Support Line (Praslin & La Digue)",
    "contact.supportLineSingleDealers": "Support Line (Single Dealers)",
    "contact.phoneSupportDesc": "Call us for immediate assistance with your queries",
    "contact.emailSupportDesc": "Send us your questions and we'll respond within 24 hours",
    "contact.officeLocationDesc": "Visit our main office in Victoria, Mahé",
    "contact.responseTime": "Response time: Within 24 hours",
    "contact.available247": "Available 24/7",
    "contact.mondayFriday": "Monday - Friday: 8:00 AM - 5:00 PM",
    "contact.saturday": "Saturday: 9:00 AM - 1:00 PM",
    "contact.sunday": "Sunday: Closed",
    "contact.urgentIssues": "For urgent issues",
    "contact.networkOutages": "Network outages and emergencies",

    // Transaction report page
    "transaction-report.title": "Total Transactions Report",
    "transaction-report.subtitle": "Transaction volume analysis and success rates",
    "transaction-report.export": "Export Report",
    "transaction-report.back": "Back to Reports",
    "transaction-report.total": "Total Transactions",
    "transaction-report.success-rate": "Success Rate",
    "transaction-report.daily-avg": "Daily Average",
    "transaction-report.active-customers": "Active Customers",
    "transaction-report.monthly-analysis": "Monthly Transaction Analysis",
    "transaction-report.type-breakdown": "Transaction Types Breakdown",
    "transaction-report.all": "All Transactions",
    "transaction-report.topup": "Mobile Recharge",
    "transaction-report.package": "Package Purchase",
    "transaction-report.bill": "Bill Payment",
    "transaction-report.sim": "SIM Sale",

    // Topup/Recharge page
    "topup.title": "Recharge",
    "topup.subtitle": "Mobile account recharge functionality",
    "topup.mobile-number": "Mobile Number",
    "topup.enter-mobile": "Enter the mobile number to recharge",
    "topup.enter-number": "Enter Mobile Number",
    "topup.phone-digits": "Phone number must be 7 digits",
    "topup.scan-qr": "Scan QR Code",
    "topup.recharge-amount": "Recharge Amount",
    "topup.select-amount": "Select or enter amount in SCR",
    "topup.custom-amount": "Custom Amount",
    "topup.enter-amount": "Enter amount",
    "topup.amount-range": "Amount must be between SCR 1 and SCR 5000",
    "topup.proceed-payment": "Proceed to Payment",
    "topup.info-title": "Recharge Information",
    "topup.quick-amounts": "Quick Amounts:",
    "topup.basic-recharge": "SCR 50 - Basic recharge",
    "topup.regular-usage": "SCR 100-500 - Regular usage",
    "topup.heavy-usage": "SCR 1000+ - Heavy usage",
    "topup.features": "Features:",
    "topup.instant-credit": "Instant credit transfer",
    "topup.qr-scanning": "QR code scanning",
    "topup.custom-support": "Custom amount support",

    // Packages page
    "packages.title": "Purchase Packages",
    "packages.subtitle": "Select and purchase mobile service packages",
    "packages.mobile-number": "Mobile Number",
    "packages.enter-number": "Enter Mobile Number",
    "packages.popular": "Popular",
    "packages.data": "Data",
    "packages.voice": "Voice",
    "packages.combo": "Combo",
    "packages.sms": "SMS",
    "packages.selected-package": "Selected Package",
    "packages.purchase": "Purchase Package",
    "packages.enter-valid": "Enter a valid mobile number to see available packages for your account type.",
    "packages.prepaid": "Prepaid",
    "packages.postpaid": "Postpaid",

    // Wallet page
    "wallet.title": "My Wallets",
    "wallet.subtitle": "Manage your account balances and transaction history",
    "wallet.recharge-balance": "Recharge Balance",
    "wallet.billpay-balance": "Bill-Pay Balance",
    "wallet.available-balance": "Available Balance",
    "wallet.add-funds": "Add Funds",
    "wallet.transfer": "Transfer",
    "wallet.quick-actions": "Quick Actions",
    "wallet.fund-request": "Fund Request",
    "wallet.transfer-funds": "Transfer Funds",
    "wallet.mobile-topup": "Mobile TopUp",
    "wallet.pay-bills": "Pay Bills",
    "wallet.transaction-history": "Transaction History",
    "wallet.all-transactions": "All Transactions",
    "wallet.recharge": "Recharge",
    "wallet.billpay": "Bill-Pay",
    "wallet.all-time": "All Time",
    "wallet.today": "Today",
    "wallet.this-week": "This Week",
    "wallet.this-month": "This Month",
    "wallet.balance-summary": "Balance Summary",
    "wallet.total-balance": "Total Balance",
    "wallet.completed": "completed",
    "wallet.description": "Manage your recharge and bill payment balances",
    "wallet.prepaid": "Prepaid",
    "wallet.postpaid": "Postpaid",
    "wallet.billPayBalance": "Bill-Pay Balance",

    // Bills page
    "bills.title": "Bill Payment",
    "bills.subtitle": "Pay utility bills for broadband and mobile services",
    "bills.account-lookup": "Account Lookup",
    "bills.account-number": "Account Number",
    "bills.enter-account": "Enter Account Number",
    "bills.lookup-bill": "Lookup Bill",
    "bills.looking-up": "Looking up...",
    "bills.detected": "Detected:",
    "bills.broadband": "Broadband",
    "bills.mobile": "Mobile",
    "bills.service": "Service",
    "bills.sample-accounts": "Sample Account Numbers for Testing:",
    "bills.click-autofill": "Click on any account number above to auto-fill and test the bill lookup feature",
    "bills.payment-options": "Payment Options",
    "bills.full-payment": "Full Bill Payment",
    "bills.custom-amount": "Custom Amount",
    "bills.payment-amount": "Payment Amount",
    "bills.proceed-payment": "Proceed to Payment",
    "bills.no-bill-found": "No bill found for account number:",
    "bills.check-number": "Please check the account number and try again.",
    "bills.supported-services": "Supported Services",
    "bills.broadband-services": "Broadband Services:",
    "bills.mobile-services": "Mobile Services:",
    "bills.description": "Pay your broadband and mobile service bills",
    "bills.clickToTest": "Click to test",

    // SIM Sales page
    "sim.title": "SIM Sales",
    "sim.subtitle": "Sell SIM cards to customers",
    "sim.local": "Local Customers",
    "sim.local-desc": "For Seychellois residents",
    "sim.gop": "GOP Holders",
    "sim.gop-desc": "Gainful Occupation Permit holders",
    "sim.tourist": "Tourists",
    "sim.tourist-desc": "For visitors to Seychelles",
    "sim.quick-tips": "Quick Tips",
    "sim.local-tip": "Local Customers:",
    "sim.local-tip-desc": "Require valid Seychelles ID and district information",
    "sim.gop-tip": "GOP Holders:",
    "sim.gop-tip-desc": "Need work permit verification and employment details",
    "sim.tourist-tip": "Tourists:",
    "sim.tourist-tip-desc": "Passport required with nationality selection",
    "sim.documentation-tip": "Documentation:",
    "sim.documentation-tip-desc": "All customers need photo capture and ID scanning",
    "sim.start-onboarding": "Start Onboarding",
    "sim.full-service": "Full service access",
    "sim.district-required": "District/sub-district required",
    "sim.local-id": "Local ID verification",
    "sim.work-permit": "Work permit verification",
    "sim.employment-auth": "Employment authorization",
    "sim.nationality": "Nationality selection",
    "sim.temporary-service": "Temporary service",
    "sim.tourist-packages": "Tourist packages available",

    // Inventory page
    "inventory.title": "SIM Inventory Management",
    "inventory.subtitle": "Track and manage SIM card inventory across all locations",
    "inventory.search": "Search SIM Cards",
    "inventory.search-placeholder": "Search by ID, ICCID, or MSISDN...",
    "inventory.filter-status": "Status",
    "inventory.filter-type": "Type",
    "inventory.filter-location": "Location",
    "inventory.all-status": "All Statuses",
    "inventory.all-types": "All Types",
    "inventory.all-locations": "All Locations",
    "inventory.available": "Available",
    "inventory.active": "Active",
    "inventory.activated": "Activated",
    "inventory.suspended": "Suspended",
    "inventory.deactivated": "Deactivated",
    "inventory.reserved": "Reserved",
    "inventory.prepaid": "Prepaid",
    "inventory.postpaid": "Postpaid",
    "inventory.iccid": "ICCID",
    "inventory.msisdn": "MSISDN",
    "inventory.sim-id": "SIM ID",
    "inventory.serial": "Serial Number",
    "inventory.type": "Type",
    "inventory.status": "Status",
    "inventory.plan": "Plan",
    "inventory.location": "Location",
    "inventory.activation-date": "Activation Date",
    "inventory.expiry-date": "Expiry Date",
    "inventory.total-sims": "Total SIM Cards",
    "inventory.low-stock": "Low Stock Alert",
    "inventory.items": "items",
    "inventory.no-sims": "No SIM cards found",
    "inventory.adjust-search": "Try adjusting your search criteria or add new SIM cards to inventory.",

    // Jobs page
    "jobs.title": "Job Card Management",
    "jobs.subtitle": "Track and manage customer service requests and technical issues",
    "jobs.create-job": "Create Job Card",
    "jobs.search-placeholder": "Search by ID, title, or customer...",
    "jobs.filter-status": "Filter by Status",
    "jobs.filter-priority": "Filter by Priority",
    "jobs.all-statuses": "All Statuses",
    "jobs.all-priorities": "All Priorities",
    "jobs.pending": "Pending",
    "jobs.in-progress": "In Progress",
    "jobs.completed": "Completed",
    "jobs.high": "High",
    "jobs.medium": "Medium",
    "jobs.low": "Low",
    "jobs.export-report": "Export Report",
    "jobs.job-id": "Job ID",
    "jobs.customer": "Customer",
    "jobs.phone": "Phone",
    "jobs.assigned-to": "Assigned To",
    "jobs.created": "Created",
    "jobs.due-date": "Due Date",
    "jobs.no-jobs": "No job cards found",
    "jobs.adjust-search": "Try adjusting your search criteria or create a new job card.",
    "jobs.create-new": "Create New Job Card",
    "jobs.job-title": "Job Title",
    "jobs.enter-title": "Enter job title",
    "jobs.customer-name": "Customer Name",
    "jobs.enter-customer": "Enter customer name",
    "jobs.customer-mobile": "Customer Mobile Number",
    "jobs.enter-mobile": "Enter Mobile Number",
    "jobs.priority": "Priority",
    "jobs.select-priority": "Select priority",
    "jobs.assign-to": "Assign To",
    "jobs.select-agent": "Select agent",
    "jobs.description": "Description",
    "jobs.describe-issue": "Describe the issue or request in detail...",
    "jobs.cancel": "Cancel",
    "jobs.create": "Create Job Card",
    "jobs.agent": "Agent",

    // Funds page
    "funds.title": "Fund Request Center",
    "funds.subtitle": "Request and manage fund transfers",
    "funds.new-request": "New Request",
    "funds.request-id": "Request ID",
    "funds.amount": "Amount",
    "funds.type": "Type",
    "funds.status": "Status",
    "funds.date": "Date",

    // Profile page
    "profile.title": "Profile",
    "profile.subtitle": "Manage your account settings",
    "profile.personal-info": "Personal Information",
    "profile.security": "Security",
    "profile.preferences": "Preferences",
    "profile.current-password": "Current Password",
    "profile.new-password": "New Password",
    "profile.confirm-password": "Confirm New Password",
    "profile.update-password": "Update Password",

    // Support page
    "support.title": "Support Center",
    "support.subtitle": "Get help and manage support tickets",
    "support.tickets": "Support Tickets",
    "support.faq": "FAQ",
    "support.resources": "Resources",

    // Feedback page
    "feedback.title": "Feedback",
    "feedback.subtitle": "Share your feedback with us",

    // About page
    "about.title": "About",
    "about.subtitle": "Learn more about our services",

    // Notifications page
    "notifications.title": "Notifications",
    "notifications.subtitle": "View your notifications",

    // Onboarding page
    "onboarding.title": "Digital Onboarding",
    "onboarding.subtitle": "Complete customer onboarding process",
    "onboarding.description": "Streamlined digital customer onboarding process",
    "onboarding.step": "Step",
    "onboarding.of": "of",
    "onboarding.complete": "complete",
    "onboarding.id-scanning": "ID Scanning",
    "onboarding.id-scanning-desc": "Document scanning with camera",
    "onboarding.customer-details": "Customer Details",
    "onboarding.customer-details-desc": "Auto-filled form with validation",
    "onboarding.package-selection": "Package Selection",
    "onboarding.package-selection-desc": "Service plan selection",
    "onboarding.sim-selection": "SIM Selection",
    "onboarding.sim-selection-desc": "Available SIM card selection",
    "onboarding.confirmation": "Confirmation",
    "onboarding.confirmation-desc": "Digital signature and final review",
    "onboarding.id-document-scanning": "ID Document Scanning",
    "onboarding.scan-upload": "Scan or upload customer ID document",
    "onboarding.upload-document": "Upload Document",
    "onboarding.change-document": "Change Document",
    "onboarding.first-name": "First Name",
    "onboarding.last-name": "Last Name",
    "onboarding.email": "Email",
    "onboarding.phone": "Phone Number",
    "onboarding.address": "Address",
    "onboarding.district": "District",
    "onboarding.sub-district": "Sub-District",
    "onboarding.select-district": "Select district",
    "onboarding.nationality": "Nationality",
    "onboarding.select-nationality": "Select nationality",
    "onboarding.select-package": "Select a package",
    "onboarding.search-sim": "Search SIM by number or ID",
    "onboarding.scan-qr": "Scan QR",
    "onboarding.available": "Available",
    "onboarding.confirmation-signature": "Confirmation & Digital Signature",
    "onboarding.customer-summary": "Customer Summary",
    "onboarding.name": "Name",
    "onboarding.package": "Package",
    "onboarding.sim-number": "SIM Number",
    "onboarding.customer-type": "Customer Type",
    "onboarding.digital-signature": "Digital Signature",
    "onboarding.signature-area": "Customer signature area",
    "onboarding.capture-signature": "Capture Signature",
    "onboarding.complete-onboarding": "Complete Onboarding",
    "onboarding.validity": "Validity",
    "onboarding.id": "ID",
  },
  fr: {
    // Navigation sections
    "nav.main": "Navigation Principale",
    "nav.services": "Services",
    "nav.user-management": "Gestion Utilisateur",
    "nav.additional": "Supplémentaire",

    // Navigation items
    "nav.dashboard": "Tableau de bord",
    "nav.topup": "Recharge Prépayée",
    "nav.wallet": "Mon Portefeuille",
    "nav.reports": "Rapports",
    "nav.contact": "Nous Contacter",
    "nav.sim-sales": "Vente SIM",
    "nav.packages": "Forfaits",
    "nav.bills": "Paiement Factures",
    "nav.onboarding": "Intégration",
    "nav.jobs": "Cartes de Travail",
    "nav.inventory": "Inventaire",
    "nav.profile": "Profil",
    "nav.notifications": "Notifications",
    "nav.support": "Support",
    "nav.funds": "Demande de Fonds",
    "nav.feedback": "Commentaires",
    "nav.about": "À Propos",

    // Dashboard
    "dashboard.title": "Tableau de bord",
    "dashboard.subtitle": "Bon retour, gérez vos services et suivez les performances",
    "dashboard.support.title": "Support Client 24/7",
    "dashboard.support.description":
      "Notre équipe de support dédiée est là pour vous aider avec toutes vos questions et problèmes.",
    "dashboard.support.button": "Contacter le Support",
    "dashboard.popular-services": "Services Populaires",
    "dashboard.transactions": "transactions",

    // KPIs
    "kpi.sales": "Ventes d'Aujourd'hui",
    "kpi.transactions": "Transactions",
    "kpi.customers": "Clients Actifs",
    "kpi.success": "Taux de Réussite",

    // Services
    "services.title": "Services Rapides",
    "services.mobile-topup": "Recharge Mobile Prépayée", // Updated French translation for Mobile Prepaid Recharge
    "services.data-packages": "Forfaits Data",
    "services.bill-payment": "Paiement Factures",
    "services.fund-request": "Demande de Fonds",
    "services.sim-sales": "Vente SIM",
    "services.job-cards": "Cartes de Travail",

    // Transactions
    "transactions.title": "Transactions Récentes",
    "transactions.view-all": "Voir Tout",
    "transactions.pending": "En Attente",
    "transactions.completed": "Terminé",

    // Fund Request
    "funds.title": "Centre de Demande de Fonds",
    "funds.new-request": "Nouvelle Demande",
    "funds.available": "Fonds Disponibles",
    "funds.pending": "Demandes en Attente",
    "funds.monthly-limit": "Limite Mensuelle",

    // Support
    "support.title": "Support & Notifications",
    "support.sim-not-working": "Carte SIM ne fonctionne pas",
    "support.payment-error": "Impossible de traiter le paiement",
    "support.help-docs": "Documentation d'Aide",
    "support.contact-support": "Contacter le Support",
    "support.feedback": "Donner un Avis",
    "support.customer": "Client",
    "support.high": "Élevé",

    // Theme
    "theme.blue": "Bleu",
    "theme.purple": "Violet",

    // Language
    "language.english": "English",
    "language.french": "Français",

    // Carousel
    "carousel.roaming-data": "Booster de Données Roaming",
    "carousel.5g-unlimited": "Forfaits 5G Illimités",
    "carousel.special-offer": "Offres Spéciales",
    "carousel.esim": "Solutions eSIM",

    // Reports page
    "reports.title": "Rapports",
    "reports.subtitle": "Analyses commerciales et suivi des performances",
    "reports.export": "Exporter les Données",
    "reports.today": "Aujourd'hui",
    "reports.week": "Cette Semaine",
    "reports.month": "Ce Mois",
    "reports.custom": "Plage Personnalisée",
    "reports.pick-date": "Choisir une plage de dates",
    "reports.total-sale": "Ventes Totales",
    "reports.total-transactions": "Transactions Totales",
    "reports.earnings": "Gains",
    "reports.sim-stock": "Stock SIM",
    "reports.airtime": "Achat de Crédit",
    "reports.balance": "Solde",
    "reports.quick-actions": "Actions Rapides de Rapport",
    "reports.sales-report": "Rapport des Ventes",
    "reports.customer-report": "Rapport Client",
    "reports.inventory-report": "Rapport d'Inventaire",
    "reports.description": "Voir les analyses commerciales complètes et les métriques de performance",
    "reports.customRange": "Plage Personnalisée",
    "reports.pickDateRange": "Choisir une plage de dates",
    "reports.exportData": "Exporter les Données",
    "reports.quickActionsDesc": "Accéder aux rapports et analyses fréquemment utilisés",

    // Contact page
    "contact.title": "Nous Contacter",
    "contact.subtitle": "Contactez notre équipe de support",
    "contact.phone-support": "Support Téléphonique",
    "contact.phone-desc": "Appelez-nous pour une assistance immédiate",
    "contact.email-support": "Support Email",
    "contact.email-desc": "Envoyez-nous vos questions via email",
    "contact.office-location": "Emplacement du Bureau",
    "contact.office-desc": "Visitez notre bureau principal",
    "contact.business-hours": "Heures d'Ouverture",
    "contact.customer-service": "Service Client",
    "contact.emergency-support": "Support d'Urgence",
    "contact.additional-resources": "Ressources Supplémentaires",
    "contact.call-now": "Appeler Maintenant",
    "contact.send-email": "Envoyer un Email",
    "contact.view-map": "Voir sur la Carte",
    "contact.website": "Site Web",
    "contact.callback": "Demande de Rappel",
    "contact.description": "Contactez notre équipe de support pour obtenir de l'aide",
    "contact.supportLineNorthCentral": "Ligne de Support (Nord & Centre)",
    "contact.supportLineSouthCentral": "Ligne de Support (Sud & Centre)",
    "contact.supportLinePraslinLaDigue": "Ligne de Support (Praslin & La Digue)",
    "contact.supportLineSingleDealers": "Ligne de Support (Revendeurs Uniques)",
    "contact.phoneSupportDesc": "Appelez-nous pour une assistance immédiate avec vos questions",
    "contact.emailSupportDesc": "Envoyez-nous vos questions et nous répondrons dans les 24 heures",
    "contact.officeLocationDesc": "Visitez notre bureau principal à Victoria, Mahé",
    "contact.responseTime": "Temps de réponse: Dans les 24 heures",
    "contact.available247": "Disponible 24/7",
    "contact.mondayFriday": "Lundi - Vendredi: 8h00 - 17h00",
    "contact.saturday": "Samedi: 9h00 - 13h00",
    "contact.sunday": "Dimanche: Fermé",
    "contact.urgentIssues": "Pour les problèmes urgents",
    "contact.networkOutages": "Pannes de réseau et urgences",

    // Transaction report page
    "transaction-report.title": "Rapport des Transactions Totales",
    "transaction-report.subtitle": "Analyse du volume des transactions et taux de réussite",
    "transaction-report.export": "Exporter le Rapport",
    "transaction-report.back": "Retour aux Rapports",
    "transaction-report.total": "Transactions Totales",
    "transaction-report.success-rate": "Taux de Réussite",
    "transaction-report.daily-avg": "Moyenne Quotidienne",
    "transaction-report.active-customers": "Clients Actifs",
    "transaction-report.monthly-analysis": "Analyse Mensuelle des Transactions",
    "transaction-report.type-breakdown": "Répartition par Type de Transaction",
    "transaction-report.all": "Toutes les Transactions",
    "transaction-report.topup": "Recharge Mobile",
    "transaction-report.package": "Achat de Forfait",
    "transaction-report.bill": "Paiement de Facture",
    "transaction-report.sim": "Vente SIM",

    // Topup/Recharge page
    "topup.title": "Recharge",
    "topup.subtitle": "Fonctionnalité de recharge de compte mobile",
    "topup.mobile-number": "Numéro de Mobile",
    "topup.enter-mobile": "Entrez le numéro de mobile à recharger",
    "topup.enter-number": "Entrer le Numéro de Mobile",
    "topup.phone-digits": "Le numéro de téléphone doit comporter 7 chiffres",
    "topup.scan-qr": "Scanner le Code QR",
    "topup.recharge-amount": "Montant de Recharge",
    "topup.select-amount": "Sélectionner ou entrer le montant en SCR",
    "topup.custom-amount": "Montant Personnalisé",
    "topup.enter-amount": "Entrer le montant",
    "topup.amount-range": "Le montant doit être entre SCR 1 et SCR 5000",
    "topup.proceed-payment": "Procéder au Paiement",
    "topup.info-title": "Informations de Recharge",
    "topup.quick-amounts": "Montants Rapides:",
    "topup.basic-recharge": "SCR 50 - Recharge de base",
    "topup.regular-usage": "SCR 100-500 - Utilisation régulière",
    "topup.heavy-usage": "SCR 1000+ - Utilisation intensive",
    "topup.features": "Fonctionnalités:",
    "topup.instant-credit": "Transfert de crédit instantané",
    "topup.qr-scanning": "Scan de code QR",
    "topup.custom-support": "Support de montant personnalisé",

    // Packages page
    "packages.title": "Acheter des Forfaits",
    "packages.subtitle": "Sélectionner et acheter des forfaits de services mobiles",
    "packages.mobile-number": "Numéro de Mobile",
    "packages.enter-number": "Entrer le Numéro de Mobile",
    "packages.popular": "Populaire",
    "packages.data": "Données",
    "packages.voice": "Voix",
    "packages.combo": "Combo",
    "packages.sms": "SMS",
    "packages.selected-package": "Forfait Sélectionné",
    "packages.purchase": "Acheter le Forfait",
    "packages.enter-valid":
      "Entrez un numéro de mobile valide pour voir les forfaits disponibles pour votre type de compte.",
    "packages.prepaid": "Prépayé",
    "packages.postpaid": "Postpayé",

    // Wallet page
    "wallet.title": "Mes Portefeuilles",
    "wallet.subtitle": "Gérer vos soldes de compte et l'historique des transactions",
    "wallet.recharge-balance": "Solde de Recharge",
    "wallet.billpay-balance": "Solde de Paiement de Factures",
    "wallet.available-balance": "Solde Disponible",
    "wallet.add-funds": "Ajouter des Fonds",
    "wallet.transfer": "Transférer",
    "wallet.quick-actions": "Actions Rapides",
    "wallet.fund-request": "Demande de Fonds",
    "wallet.transfer-funds": "Transférer des Fonds",
    "wallet.mobile-topup": "Recharge Mobile",
    "wallet.pay-bills": "Payer les Factures",
    "wallet.transaction-history": "Historique des Transactions",
    "wallet.all-transactions": "Toutes les Transactions",
    "wallet.recharge": "Recharge",
    "wallet.billpay": "Paiement de Factures",
    "wallet.all-time": "Tout le Temps",
    "wallet.today": "Aujourd'hui",
    "wallet.this-week": "Cette Semaine",
    "wallet.this-month": "Ce Mois",
    "wallet.balance-summary": "Résumé du Solde",
    "wallet.total-balance": "Solde Total",
    "wallet.completed": "terminé",
    "wallet.description": "Gérer vos soldes de recharge et de paiement de factures",
    "wallet.prepaid": "Prépayé",
    "wallet.postpaid": "Postpayé",
    "wallet.billPayBalance": "Solde de Paiement de Factures",

    // Bills page
    "bills.title": "Paiement de Factures",
    "bills.subtitle": "Payer les factures de services publics pour le haut débit et les services mobiles",
    "bills.account-lookup": "Recherche de Compte",
    "bills.account-number": "Numéro de Compte",
    "bills.enter-account": "Entrer le Numéro de Compte",
    "bills.lookup-bill": "Rechercher la Facture",
    "bills.looking-up": "Recherche en cours...",
    "bills.detected": "Détecté:",
    "bills.broadband": "Haut Débit",
    "bills.mobile": "Mobile",
    "bills.service": "Service",
    "bills.sample-accounts": "Numéros de Compte d'Exemple pour les Tests:",
    "bills.click-autofill":
      "Cliquez sur n'importe quel numéro de compte ci-dessus pour remplir automatiquement et tester la fonction de recherche de facture",
    "bills.payment-options": "Options de Paiement",
    "bills.full-payment": "Paiement Complet de la Facture",
    "bills.custom-amount": "Montant Personnalisé",
    "bills.payment-amount": "Montant du Paiement",
    "bills.proceed-payment": "Procéder au Paiement",
    "bills.no-bill-found": "Aucune facture trouvée pour le numéro de compte:",
    "bills.check-number": "Veuillez vérifier le numéro de compte et réessayer.",
    "bills.supported-services": "Services Pris en Charge",
    "bills.broadband-services": "Services Haut Débit:",
    "bills.mobile-services": "Services Mobiles:",
    "bills.description": "Payez vos factures de services haut débit et mobiles",
    "bills.clickToTest": "Cliquer pour tester",

    // SIM Sales page
    "sim.title": "Vente SIM",
    "sim.subtitle": "Vendre des cartes SIM aux clients",
    "sim.local": "Clients Locaux",
    "sim.local-desc": "Pour les résidents seychellois",
    "sim.gop": "Détenteurs de GOP",
    "sim.gop-desc": "Détenteurs de permis d'occupation lucrative",
    "sim.tourist": "Touristes",
    "sim.tourist-desc": "Pour les visiteurs aux Seychelles",
    "sim.quick-tips": "Conseils Rapides",
    "sim.local-tip": "Clients Locaux:",
    "sim.local-tip-desc": "Nécessitent une carte d'identité seychelloise valide et des informations de district",
    "sim.gop-tip": "Détenteurs de GOP:",
    "sim.gop-tip-desc": "Nécessitent une vérification du permis de travail et des détails d'emploi",
    "sim.tourist-tip": "Touristes:",
    "sim.tourist-tip-desc": "Passeport requis avec sélection de nationalité",
    "sim.documentation-tip": "Documentation:",
    "sim.documentation-tip-desc": "Tous les clients ont besoin d'une capture photo et d'un scan d'identité",
    "sim.start-onboarding": "Commencer l'Intégration",
    "sim.full-service": "Accès complet aux services",
    "sim.district-required": "District/sous-district requis",
    "sim.local-id": "Vérification d'identité locale",
    "sim.work-permit": "Vérification du permis de travail",
    "sim.employment-auth": "Autorisation d'emploi",
    "sim.nationality": "Sélection de nationalité",
    "sim.temporary-service": "Service temporaire",
    "sim.tourist-packages": "Forfaits touristiques disponibles",

    // Inventory page
    "inventory.title": "Gestion de l'Inventaire SIM",
    "inventory.subtitle": "Suivre et gérer l'inventaire des cartes SIM dans tous les emplacements",
    "inventory.search": "Rechercher des Cartes SIM",
    "inventory.search-placeholder": "Rechercher par ID, ICCID ou MSISDN...",
    "inventory.filter-status": "Statut",
    "inventory.filter-type": "Type",
    "inventory.filter-location": "Emplacement",
    "inventory.all-status": "Tous les Statuts",
    "inventory.all-types": "Tous les Types",
    "inventory.all-locations": "Tous les Emplacements",
    "inventory.available": "Disponible",
    "inventory.active": "Actif",
    "inventory.activated": "Activé",
    "inventory.suspended": "Suspendu",
    "inventory.deactivated": "Désactivé",
    "inventory.reserved": "Réservé",
    "inventory.prepaid": "Prépayé",
    "inventory.postpaid": "Postpayé",
    "inventory.iccid": "ICCID",
    "inventory.msisdn": "MSISDN",
    "inventory.sim-id": "ID SIM",
    "inventory.serial": "Numéro de Série",
    "inventory.type": "Type",
    "inventory.status": "Statut",
    "inventory.plan": "Forfait",
    "inventory.location": "Emplacement",
    "inventory.activation-date": "Date d'Activation",
    "inventory.expiry-date": "Date d'Expiration",
    "inventory.total-sims": "Total de Cartes SIM",
    "inventory.low-stock": "Alerte de Stock Faible",
    "inventory.items": "éléments",
    "inventory.no-sims": "Aucune carte SIM trouvée",
    "inventory.adjust-search":
      "Essayez d'ajuster vos critères de recherche ou d'ajouter de nouvelles cartes SIM à l'inventaire.",

    // Jobs page
    "jobs.title": "Gestion des Cartes de Travail",
    "jobs.subtitle": "Suivre et gérer les demandes de service client et les problèmes techniques",
    "jobs.create-job": "Créer une Carte de Travail",
    "jobs.search-placeholder": "Rechercher par ID, titre ou client...",
    "jobs.filter-status": "Filtrer par Statut",
    "jobs.filter-priority": "Filtrer par Priorité",
    "jobs.all-statuses": "Tous les Statuts",
    "jobs.all-priorities": "Toutes les Priorités",
    "jobs.pending": "En Attente",
    "jobs.in-progress": "En Cours",
    "jobs.completed": "Terminé",
    "jobs.high": "Élevé",
    "jobs.medium": "Moyen",
    "jobs.low": "Faible",
    "jobs.export-report": "Exporter le Rapport",
    "jobs.job-id": "ID de Travail",
    "jobs.customer": "Client",
    "jobs.phone": "Téléphone",
    "jobs.assigned-to": "Assigné à",
    "jobs.created": "Créé",
    "jobs.due-date": "Date d'Échéance",
    "jobs.no-jobs": "Aucune carte de travail trouvée",
    "jobs.adjust-search": "Essayez d'ajuster vos critères de recherche ou de créer une nouvelle carte de travail.",
    "jobs.create-new": "Créer une Nouvelle Carte de Travail",
    "jobs.job-title": "Titre du Travail",
    "jobs.enter-title": "Entrer le titre du travail",
    "jobs.customer-name": "Nom du Client",
    "jobs.enter-customer": "Entrer le nom du client",
    "jobs.customer-mobile": "Numéro de Mobile du Client",
    "jobs.enter-mobile": "Entrer le Numéro de Mobile",
    "jobs.priority": "Priorité",
    "jobs.select-priority": "Sélectionner la priorité",
    "jobs.assign-to": "Assigner à",
    "jobs.select-agent": "Sélectionner l'agent",
    "jobs.description": "Description",
    "jobs.describe-issue": "Décrire le problème ou la demande en détail...",
    "jobs.cancel": "Annuler",
    "jobs.create": "Créer la Carte de Travail",
    "jobs.agent": "Agent",

    // Funds page
    "funds.title": "Centre de Demande de Fonds",
    "funds.subtitle": "Demander et gérer les transferts de fonds",
    "funds.new-request": "Nouvelle Demande",
    "funds.request-id": "ID de Demande",
    "funds.amount": "Montant",
    "funds.type": "Type",
    "funds.status": "Statut",
    "funds.date": "Date",

    // Profile page
    "profile.title": "Profil",
    "profile.subtitle": "Gérer les paramètres de votre compte",
    "profile.personal-info": "Informations Personnelles",
    "profile.security": "Sécurité",
    "profile.preferences": "Préférences",
    "profile.current-password": "Mot de Passe Actuel",
    "profile.new-password": "Nouveau Mot de Passe",
    "profile.confirm-password": "Confirmer le Nouveau Mot de Passe",
    "profile.update-password": "Mettre à Jour le Mot de Passe",

    // Support page
    "support.title": "Centre de Support",
    "support.subtitle": "Obtenir de l'aide et gérer les tickets de support",
    "support.tickets": "Tickets de Support",
    "support.faq": "FAQ",
    "support.resources": "Ressources",

    // Feedback page
    "feedback.title": "Commentaires",
    "feedback.subtitle": "Partagez vos commentaires avec nous",

    // About page
    "about.title": "À Propos",
    "about.subtitle": "En savoir plus sur nos services",

    // Notifications page
    "notifications.title": "Notifications",
    "notifications.subtitle": "Voir vos notifications",

    // Onboarding page
    "onboarding.title": "Intégration Numérique",
    "onboarding.subtitle": "Compléter le processus d'intégration du client",
    "onboarding.description": "Processus d'intégration client numérique simplifié",
    "onboarding.step": "Étape",
    "onboarding.of": "de",
    "onboarding.complete": "terminé",
    "onboarding.id-scanning": "Scan d'Identité",
    "onboarding.id-scanning-desc": "Scan de document avec caméra",
    "onboarding.customer-details": "Détails du Client",
    "onboarding.customer-details-desc": "Formulaire auto-rempli avec validation",
    "onboarding.package-selection": "Sélection de Forfait",
    "onboarding.package-selection-desc": "Sélection du plan de service",
    "onboarding.sim-selection": "Sélection SIM",
    "onboarding.sim-selection-desc": "Sélection de carte SIM disponible",
    "onboarding.confirmation": "Confirmation",
    "onboarding.confirmation-desc": "Signature numérique et révision finale",
    "onboarding.id-document-scanning": "Scan de Document d'Identité",
    "onboarding.scan-upload": "Scanner ou télécharger le document d'identité du client",
    "onboarding.upload-document": "Télécharger le Document",
    "onboarding.change-document": "Changer le Document",
    "onboarding.first-name": "Prénom",
    "onboarding.last-name": "Nom",
    "onboarding.email": "Email",
    "onboarding.phone": "Numéro de Téléphone",
    "onboarding.address": "Adresse",
    "onboarding.district": "District",
    "onboarding.sub-district": "Sous-District",
    "onboarding.select-district": "Sélectionner le district",
    "onboarding.nationality": "Nationalité",
    "onboarding.select-nationality": "Sélectionner la nationalité",
    "onboarding.select-package": "Sélectionner un forfait",
    "onboarding.search-sim": "Rechercher SIM par numéro ou ID",
    "onboarding.scan-qr": "Scanner QR",
    "onboarding.available": "Disponible",
    "onboarding.confirmation-signature": "Confirmation & Signature Numérique",
    "onboarding.customer-summary": "Résumé du Client",
    "onboarding.name": "Nom",
    "onboarding.package": "Forfait",
    "onboarding.sim-number": "Numéro SIM",
    "onboarding.customer-type": "Type de Client",
    "onboarding.digital-signature": "Signature Numérique",
    "onboarding.signature-area": "Zone de signature du client",
    "onboarding.capture-signature": "Capturer la Signature",
    "onboarding.complete-onboarding": "Terminer l'Intégration",
    "onboarding.validity": "Validité",
    "onboarding.id": "ID",
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en")
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
    const savedLanguage = localStorage.getItem("language") as Language
    console.log("[v0] Loading saved language from localStorage:", savedLanguage)
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "fr")) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (newLanguage: Language) => {
    console.log("[v0] Changing language from", language, "to", newLanguage)
    setLanguage(newLanguage)
    localStorage.setItem("language", newLanguage)
    console.log("[v0] Language changed and saved to localStorage")
  }

  const t = (key: string): string => {
    const translation = translations[language][key as keyof (typeof translations)[typeof language]]
    if (!translation) {
      console.warn("[v0] Missing translation for key:", key, "in language:", language)
      return key
    }
    return translation
  }

  if (!mounted) {
    return null
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
